Ext.define('Buzzor.singx.singx.model.backoffice.singx.CustomerContaDTOModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "customerId"
     }, {
          "name": "countryId"
     }, {
          "name": "customerTypeId"
     }, {
          "name": "emailId"
     }, {
          "name": "residenceTypeId"
     }, {
          "name": "nationalityId"
     }, {
          "name": "documentId"
     }, {
          "name": "idProofValue"
     }, {
          "name": "expiryDate"
     }, {
          "name": "mapId"
     }, {
          "name": "companyTypeId"
     }, {
          "name": "companyCategoryId"
     }, {
          "name": "companyName"
     }, {
          "name": "registrationNumber"
     }, {
          "name": "headOffice"
     }, {
          "name": "contactId"
     }, {
          "name": "phoneNumber"
     }, {
          "name": "prefixId"
     }, {
          "name": "firstName"
     }, {
          "name": "middleName"
     }, {
          "name": "lastName"
     }, {
          "name": "genderId"
     }, {
          "name": "dateOfBirth"
     }, {
          "name": "phoneCountryCode"
     }]
});