Ext.define('Buzzor.singx.shared.singx.model.singx.BankBranchModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "branchId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "branchName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "branchCode",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bankid",
          "reference": "Bank",
          "defaultValue": ""
     }, {
          "name": "countryid",
          "reference": "Country",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});