Ext.define('Buzzor.singx.shared.singx.model.singx.CfgDocIndividualModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "documentId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "documentName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "isReferenceNoReqd",
          "type": "boolean",
          "defaultValue": ""
     }, {
          "name": "isIssueDateReqd",
          "type": "boolean",
          "defaultValue": ""
     }, {
          "name": "isExpiryDateReqd",
          "type": "boolean",
          "defaultValue": ""
     }, {
          "name": "remarks",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "isMandatory",
          "type": "boolean",
          "defaultValue": ""
     }, {
          "name": "displaySeq",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "maxSize",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "residencetypeid",
          "reference": "ResidenceType",
          "defaultValue": ""
     }, {
          "name": "countryid",
          "reference": "Country",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});