Ext.define('Buzzor.singx.shared.singx.model.singx.CorporateRegDetailModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "mapId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "customerid",
          "reference": "SingXCustomer",
          "defaultValue": ""
     }, {
          "name": "companytypeid",
          "reference": "CompanyType",
          "defaultValue": ""
     }, {
          "name": "companycategoryid",
          "reference": "CompanyCategory",
          "defaultValue": ""
     }, {
          "name": "companyName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "registrationNumber",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "headOffice",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "annualTurnOver",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});