Ext.define('Buzzor.singx.shared.singx.model.singx.CustomerXContactsModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "mapPk",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "contactid",
          "reference": "SingxContacts",
          "defaultValue": ""
     }, {
          "name": "customerid",
          "reference": "SingXCustomer",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});